name: 'Install bun and dependencies'
description: 'Installs a specific version of bun and project dependencies'
inputs:
  bun-version:
    description: 'The version of bun to install.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Installing bun v${{ inputs.bun-version }}
      id: install-bun
      working-directory: ${{ github.action_path }}
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
    - name: Install dependencies
      id: install-deps
      working-directory: ${{ github.action_path }}
      shell: bash
      run: bun install
