name: 'Install bun and dependencies'
description: 'Installs a specific version of bun and project dependencies'
inputs:
  bun-version:
    description: 'The version of bun to install.'
    required: true
  workdir:
    description: "Working directory relative to the caller's workspace"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Installing bun v${{ inputs.bun-version }}
      id: install-bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
    - name: Change working directory to ${{ inputs.workdir }}
      shell: bash
      run: |
        cd "${{ inputs.workdir }}"
    - run: ls
      shell: bash
    - name: Working dir
      run: pwd
      shell: bash
    - name: Install dependencies
      id: install-deps
      shell: bash
      run: bun install
